[project]
name = "repl-nix-new-repl"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.0",
    "pandas>=2.2.3",
    "pydeck>=0.9.1",
    "streamlit>=1.41.0",
]
